GraficaOnline/Controllers/CarrinhoCompraController.cs
using GraficaOnline.Models;
using GraficaOnline.Repositories;
using GraficaOnline.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace GraficaOnline.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IProdutoRepository produtoRepository, CarrinhoCompra carrinhoCompra)
        {
            _produtoRepository = produtoRepository;
            _carrinhoCompra = carrinhoCompra;
        }
        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }
        [Authorize]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int produtoId)
        {
            var produtoSelecionado = _produtoRepository.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produtoSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(produtoSelecionado, 1);
            }
            return RedirectToAction("Index");
        }
        [Authorize]
        public IActionResult RemoverItemDoCarrinhoCompra(int produtoId)
        {
            var produtoSelecionado = _produtoRepository.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);
            if (produtoSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(produtoSelecionado);
            }
            return RedirectToAction("Index");
        }

    }
}

GraficaOnline/Views/Shared/_Carousel.cshtml
<div id="carouselProdutos" class="carousel slide marginTop1" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselProdutos" data-slide-to="0" class="active"></li>
        <li data-target="#carouselProdutos" data-slide-to="1"></li>
        <li data-target="#carouselProdutos" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/CarouselCamisaPreta.jpg" class="d-block" width="1000" height="500" alt="Produto">
        </div>
        <div class="carousel-item">
            <img src="~/images/CarouselCanecaPreta.jpg"  class="d-block" width="1000" height="500" alt="Produto">
            <div class="carousel-caption">
                <h3 class="font-weight-bold text-dark">Canecas personalizadas</h3>
                <p class="text-dark">Envie sua Arte para nós!</p>
            </div>
            <div class="carousel-caption">
                <h3 class="font-weight-bold text-dark">Camisas personalizadas</h3>
                <p class="text-dark">Envie sua Arte para nós!</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/CarouselCopoPreto.jpg" class="d-block"  width="1000" height="500" alt="Produto">
            <div class="carousel-caption">
                <h3 class="font-weight-bold text-dark">Copos para festa</h3>
                <p class="text-dark">Envie sua Arte para nós!</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselProdutos" data-slide="prev">
        <span class="carousel-control-prev-icon font-weight-bold text-dark"></span>
    </a>
    <a class="carousel-control-next" href="#carouselProdutos" data-slide="next">
        <span class="carousel-control-next-icon font-weight-bold text-dark"></span>
    </a>
</div>

GraficaOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Gráfica online</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
            /* Set the size of the div element that contains the map */
            #map {
                height: 350px; /* The height is 400 pixels */
                width: 100%; /* The width is the width of the web page */
            }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gráfica online</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>

                    @await Component.InvokeAsync("CategoriaMenu")

                    @if (User.IsInRole("Admin"))
                    {
                        <a class="nav-link text-light float-right" asp-area="Admin" asp-controller="Admin" asp-action="Index">Administração</a>
                    }

                    <form class="navbar-right mt-3 ml-3" asp-controller="Produto" asp-action="Search" method="get">
                        <div class="form-group float-right">
                            <input type="text" class="form-control col-12" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                        </div>
                    </form>

                        @await Html.PartialAsync("_LoginPartial")


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Gráfica online
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

GraficaOnline/Views/Shared/_ProdutosResumo.cshtml
@model Produto


<div class="col-md-4 col-sm-4 col-lg-4">
    <img src="@Model.ImagemUrl" class="card-img-top imageProduto" alt="@Model.Nome" />
    <div class="figure-caption">
        <h4 class="formPullRightButton">@Model.ValorVenda.ToString("c")</h4>
        <h4>
            <a asp-controller="Produto" asp-action="Details" asp-route-produtoId="@Model.ProdutoId">@Model.Nome</a>
        </h4>
        <h6>@Model.Descricao</h6>
    </div>
    <div text-right">
        <p class="formPullRightButton">
            <a class="btn btn-primary" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-produtoId="@Model.ProdutoId">
                Incluir no Carrinho
            </a>
        </p>
    </div>
</div>